export default [
  {
    path: '/products',
    name: 'products',
    component: () => import('@/components/Layouts/Public.vue'),
    meta: {
      title: 'Products',
      sort: 5,
      withSubmenu: true,
      external: true,
      excludeFromRoot: true,
      authenticatable: false,
      icon: 'mdi-book-multiple-variant',
    },
    children: [
      {
        path: 'e-learning',
        name: 'products.elearning',
        component: () => import('../eLearning.vue'),
        meta: {
          title: 'e-Learning',
          sort: 5,
          external: true,
          excludeFromRoot: true,
          authenticatable: false,
          icon: 'mdi-book-multiple-variant',
        },
      },
      {
        path: 'mobile-apps',
        name: 'products.application',
        component: () => import('../MobileApp.vue'),
        meta: {
          title: 'Mobile Apps',
          sort: 5,
          external: true,
          excludeFromRoot: true,
          authenticatable: false,
          icon: 'mdi-book-multiple-variant',
        },
      },
      {
        path: 'augmented-reality',
        name: 'products.augmentedreality',
        component: () => import('../AugmentedReality.vue'),
        meta: {
          title: 'Augmented Reality',
          sort: 5,
          external: true,
          excludeFromRoot: true,
          authenticatable: false,
          icon: 'mdi-book-multiple-variant',
        },
      },
      {
        path: 'management-systems',
        name: 'products.systems',
        component: () => import('../systems/ManagementSystem.vue'),
        meta: {
          title: 'Management Systems',
          sort: 5,
          external: true,
          excludeFromRoot: true,
          authenticatable: false,
          icon: 'mdi-book-multiple-variant',
        },
      },
      {
        path: 'management-systems/lms',
        name: 'systems.lms',
        component: () => import('../systems/LMS.vue'),
        meta: {
          title: 'LMS',
          sort: 5,
          external: true,
          excludeFromRoot: true,
          authenticatable: false,
          icon: 'mdi-book-multiple-variant',
        },
      },
      {
        path: 'management-systems/cms',
        name: 'systems.cms',
        component: () => import('../systems/CMS.vue'),
        meta: {
          title: 'CMS',
          sort: 5,
          external: true,
          excludeFromRoot: true,
          authenticatable: false,
          icon: 'mdi-book-multiple-variant',
        },
      },
      {
        path: 'management-systems/hrms',
        name: 'systems.hrms',
        component: () => import('../systems/HRMS.vue'),
        meta: {
          title: 'HRMS',
          sort: 5,
          external: true,
          excludeFromRoot: true,
          authenticatable: false,
          icon: 'mdi-book-multiple-variant',
        },
      },
    ]
  },
]
